version: '3.6'
services:
  database:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: store_site
    volumes:
      - habrdb-data:/var/lib/postgresql/data
    ports:
      - "15432:5432"

  cache:
    image: redis:7
    restart: always
    ports:
      - '16379:6379'
    volumes:
      - cache:/data

volumes:
  cache:
  habrdb-data:
