# Generated by Django 4.2.4 on 2023-08-27 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_users_basket_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукти'},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name': 'Категорія', 'verbose_name_plural': 'Категорії'},
        ),
    ]
